version: '3.8'

services:
  dxs2api:
    container_name: dxs2api
    image: 958527256docker/dxs2api:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DEEPSEEK_API_URL=https://chat.zju.edu.cn
      - DXS_AUTHORIZATION=your_deepseek_token  # 替换为您的实际token
      - RATE_LIMIT=60
    volumes:
      - ./logs:/app/logs  # 可选：挂载日志目录
    networks:
      - dxs_network

networks:
  dxs_network:
    driver: bridge